import type { Program } from "./types";

export const programs: Program[] = [
  {
    slug: "programming-for-teens",
    image: "/images/programs/programming-for-teens.jpg",
    tag: "01 / teens",
    name: "Programming for Teens",
    blurb: "First lines of code to first real projects.",
    desc: "A hands-on introduction to programming for teenagers across Trinidad & Tobago. Students go from their very first line of code to building small projects they can show off, and a way of thinking they keep forever.",
    who: "Ages 13–19",
    format: "Weekly sessions",
    points: [
      { n: "01", text: "Fundamentals of programming, taught from zero, no experience needed" },
      { n: "02", text: "Small-group sessions led by volunteer engineers and educators" },
      { n: "03", text: "A finished project to present at graduation" },
      { n: "04", text: "A pathway into further study and our alumni community" },
    ],
    quote: "I was always interested in computers... I think the skills I got would be useful in the future.",
    quoteBy: "graduate · programming for teens",
    whyTitle: "Talent is everywhere. Opportunity isn't.",
    why: "All over Trinidad & Tobago there are teenagers who would love to build software but have never met a programmer, never seen a line of code, and can't afford a course. One free class changes that arithmetic. Our graduates leave with a project, a certificate, and something harder to measure: proof that this world is theirs too.",
    tiers: [
      { amt: "$100", what: "Materials for one student", note: "Workbooks and course materials for a full cohort run." },
      { amt: "$350", what: "A student's full seat", note: "Everything one teen needs to go from zero to demo day." },
      { amt: "$1500", what: "A classroom session", note: "Space, equipment, and materials for a whole class." },
    ],
    ctaLine: "Put the next teen in front of their first line of code.",
  },
  {
    slug: "adult-tech-literacy",
    image: "/images/programs/adult-tech-literacy.jpg",
    tag: "02 / adults",
    name: "Adult Technology Literacy",
    blurb: "From first click to confident everyday use.",
    desc: "For adults with little or no exposure to computers. We start with the mouse and keyboard and end with confident, independent use of email, documents, and everyday online services.",
    who: "Adults, all ages",
    format: "Community classes",
    points: [
      { n: "01", text: "Patient, judgement-free teaching from the very first click" },
      { n: "02", text: "Practical skills: email, documents, online forms and services" },
      { n: "03", text: "Staying safe online: passwords, scams, and privacy" },
      { n: "04", text: "A certificate and ongoing support after graduation" },
    ],
    quote: "I never thought at my age I would be sending emails on my own. Now I help my grandchildren with their schoolwork.",
    quoteBy: "graduate · adult technology literacy",
    whyTitle: "The digital world shouldn't leave anyone behind.",
    why: "Banking, government forms, staying in touch with family. Everyday life has moved online, and adults who never got a fair introduction are quietly locked out. Our classes start from the very first click, with no judgement and no jargon. Graduates don't just gain skills; they gain back their independence.",
    tiers: [
      { amt: "$100", what: "Class materials for one learner", note: "Printed guides made for absolute beginners." },
      { amt: "$400", what: "A learner's full course", note: "Every session, from first click to certificate." },
      { amt: "$1200", what: "A community class", note: "A full literacy course for a neighbourhood group." },
    ],
    ctaLine: "Help an adult log in to the world everyone else takes for granted.",
  },
  {
    slug: "computers-for-kids",
    image: "/images/programs/computers-for-kids.jpg",
    tag: "03 / kids",
    name: "Computers for Kids",
    blurb: "Donated machines that keep school within reach.",
    desc: "We collect, refurbish, and deliver computers to families whose children would otherwise be locked out of online learning. Over 60 machines placed so far, and each one is a doorway back into the classroom.",
    who: "School-age children",
    format: "Hardware donation",
    points: [
      { n: "01", text: "A refurbished, ready-to-use computer delivered to the family" },
      { n: "02", text: "Setup and a starter orientation for parents and kids" },
      { n: "03", text: "Priority for households affected by school closures" },
      { n: "04", text: "Follow-up support if the machine has trouble" },
    ],
    quote: "It feels nice to know somebody thought of us and reached out to help.",
    quoteBy: "parent · computers for kids",
    whyTitle: "No child should miss school for want of a machine.",
    why: "When learning moved online, children without a computer at home simply disappeared from the classroom. A refurbished machine, one many offices would have thrown away, puts them back at their desk. We collect, restore, deliver, and set up each one, and we stay in touch in case it needs fixing.",
    tiers: [
      { amt: "$200", what: "Parts & refurbishment", note: "Drives, memory, and repairs to revive one machine." },
      { amt: "$800", what: "A complete computer", note: "Refurbished, delivered, and set up for one family." },
      { amt: "$2500", what: "A classroom's worth", note: "Several machines for a school or community centre." },
    ],
    ctaLine: "Put a child back in the classroom with one machine.",
  },
  {
    slug: "youth-speak-up",
    image: "/images/programs/youth-speak-up.png",
    tag: "04 / youth",
    name: "Youth Speak UP!",
    blurb: "A platform for young voices in tech and community.",
    desc: "A community initiative that gives young people the space, tools, and confidence to speak up about the issues that shape their futures, with technology as the megaphone.",
    who: "Young people",
    format: "Community events",
    points: [
      { n: "01", text: "Workshops on communicating and presenting with digital tools" },
      { n: "02", text: "A stage, online and in person, for youth perspectives" },
      { n: "03", text: "Mentorship from volunteers across the foundation" },
      { n: "04", text: "Connections to our other training programs" },
    ],
    quote: "For the first time somebody asked what WE think, and then handed us the mic.",
    quoteBy: "participant · youth speak up!",
    whyTitle: "Young voices, amplified by technology.",
    why: "Policies about young people are usually made without them in the room. Youth Speak UP! flips that: we teach young people to present, publish, and broadcast their perspectives with digital tools, then give them a real stage. Confidence built here spills into school, work, and every one of our other programs.",
    tiers: [
      { amt: "$150", what: "A workshop seat", note: "Presentation and digital-media training for one youth." },
      { amt: "$500", what: "An event platform", note: "Sound, streaming, and space for a youth forum." },
      { amt: "$1000", what: "A full campaign", note: "A season of workshops leading to a public showcase." },
    ],
    ctaLine: "Hand the mic to the next young voice.",
  },
  {
    slug: "hamper-drive",
    image: "/images/programs/hamper-drive.jpg",
    tag: "05 / community",
    name: "Hamper Donation Drive",
    blurb: "110+ goodwill hampers delivered to local communities.",
    desc: "Technology matters most when basic needs are met. Our hamper drives deliver food and essentials to households across Trinidad & Tobago. Over 110 hampers and counting.",
    who: "Families in need",
    format: "Seasonal drives",
    points: [
      { n: "01", text: "Food and essential supplies for a household" },
      { n: "02", text: "Delivered directly by our volunteer network" },
      { n: "03", text: "Priority for communities hit hardest by hardship" },
      { n: "04", text: "A door-opener to our training and hardware programs" },
    ],
    quote: "It feels nice to know somebody thought of us and reached out to help.",
    quoteBy: "recipient · hamper donation drive",
    whyTitle: "First the table, then the desk.",
    why: "Nobody learns to code on an empty stomach. Our hamper drives exist because technology charity means nothing if a family is struggling for essentials. Each hamper is packed and delivered by volunteers, and it often becomes the first conversation that brings a household into our classes and computer programs.",
    tiers: [
      { amt: "$250", what: "One family hamper", note: "Food and essentials, delivered to the door." },
      { amt: "$1000", what: "Four hampers", note: "A street's worth of goodwill in one gift." },
      { amt: "$2500", what: "A community drive", note: "Hampers for ten households in one area." },
    ],
    ctaLine: "Deliver the hamper that starts a bigger story.",
  },
  {
    slug: "girls-in-ict",
    image: "/images/programs/girls-in-ict.jpg",
    tag: "06 / girls in ict",
    name: "Girls in ICT Day",
    blurb: "Encouraging the next generation of women in technology.",
    desc: "Our annual campaign for International Girls in ICT Day, showing girls across T&T that careers in technology are for them, through talks, showcases, and hands-on sessions.",
    who: "Girls & young women",
    format: "Annual campaign",
    points: [
      { n: "01", text: "Hands-on tech sessions built for first-timers" },
      { n: "02", text: "Role models and speakers from the local tech community" },
      { n: "03", text: "Pathways into Programming for Teens and beyond" },
      { n: "04", text: "A growing network of girls who click start" },
    ],
    quote: "I didn't know girls did this. Now I want to build my own app.",
    quoteBy: "participant · girls in ict day",
    whyTitle: "She can't be what she can't see.",
    why: "Across the Caribbean, girls opt out of technology long before the job market does it for them. Not for lack of ability, but for lack of role models. One day a year, we fill the room with women who build things and girls who are about to. The talks end; the ambitions don't.",
    tiers: [
      { amt: "$150", what: "A girl's full day", note: "Sessions, materials, and lunch for one participant." },
      { amt: "$600", what: "A hands-on lab", note: "Kit and mentors for a small-group tech session." },
      { amt: "$2000", what: "The main stage", note: "Venue and production for the annual showcase." },
    ],
    ctaLine: "Show a girl that tech was always for her.",
  },
];

export const programSlugs = programs.map((p) => p.slug);

export function getProgram(slug: string): Program | undefined {
  return programs.find((p) => p.slug === slug);
}
